{{ config(
    materialized = 'table',
    schema = 'ECOESSENTIALS_DW_SOURCE'
    )
}}

SELECT
CUSTOMER_ID as CUSTOMER_KEY,
CUSTOMER_ID,
CUSTOMER_FIRST_NAME,
CUSTOMER_LAST_NAME,
CUSTOMER_PHONE,
CUSTOMER_ADDRESS,
CUSTOMER_CITY,
CUSTOMER_STATE,
CUSTOMER_ZIP,
CUSTOMER_COUNTRY,
CUSTOMER_EMAIL 
FROM {{source("ecoessentials_landing", 'CUSTOMER')}}